name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
    build:
        name: Build Projects
        runs-on: [sef-hosted, Windows, X64]
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4.2.2

        - name: Compile EmissaoMicroservice
          run: |
            boss i
            c:\temp\build.bat . "EmissaoMicroservice.dproj"

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name: build-artfacts
            path: |
                EmissaoMicroservice\bin\EmissaoMicroservice
