name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Projects
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3                    

    - name: Compile EmissaoMicroservice
      run: |
        cd EmissaoMicroservice 
        boss i
        c:\temp\build.bat . "EmissaoMicroservice.dproj"

    - name: Compile AuthMicroservice
      run: | 
        cd AuthMicroservice
        boss i
        c:\temp\build.bat . "AuthMicroservice.dproj"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: build-artifacts
        path: |
          EmissaoMicroservice\bin\EmissaoMicroservice
          AuthMicroservice\bin\AuthMicroservice