name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Projects
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3                    

    - name: Compile EmissaoMicroservice
      run: |
        boss i
        c:\temp\build.bat . "EmissaoMicroservice.dproj"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: build-artifacts
        path: |
          bin\EmissaoMicroservice
  
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    needs: build
    steps:
    - name: Parando seriço
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sudo systemctl stop emissao.service

    - name: Download Build
      uses: actions/download-artifact@v4.1.8
      with:
        name: build-artifacts
        path: ./artifacts

    - name: Deploy da API Emissao
      uses: nogsantos/scp-deploy@master
      with:
        src: ./artifacts/emissaomicroservice/bin/EmissaoMicroservice
        host: ${{ secrets.SSH_HOST }}
        remote: ${{ secrets.SSH_DIR }}
        port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}

    - name: Inicando serviço
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sudo systemctl start emissao.service
